const termsEn = `GACHI Terms of Service

Effective Date: April 15, 2026
Thank you for using GACHI (the "Service").
These Terms of Service set out the rights, obligations, and responsibilities between the Service and its members, along with other necessary provisions.

Article 1 (Purpose)
These Terms govern the use of the mobile application and related services provided by GACHI, and are intended to define the rights, obligations, and responsibilities between the Service and its members.

Article 2 (Definitions)
The following terms are used in these Terms as defined below:
• "Service" means the school notice translation, summarization, explanation, action guides, schedule management, and all ancillary features provided by GACHI.
• "Member" means a person who has agreed to these Terms, registered an account, and is using the Service.
• "Account" means the ID and password set by a member for identification and use of the Service.
• "Content" means text, images, documents, child information, school information, and other materials uploaded, registered, entered, or generated by a member during use of the Service.

Article 3 (Posting and Amendment of Terms)
1. The Service shall post these Terms on the registration screen or a separate screen within the Service so that members can easily review them.
2. The Service may amend these Terms to the extent permitted by applicable law.
3. When amending the Terms, the Service shall announce the effective date and reason for amendment at least 7 days before the effective date. However, if the amendment is unfavorable to members, notice shall be given at least 30 days in advance.
4. If a member continues to use the Service after the effective date of the amended Terms, the member is deemed to have agreed to the amended Terms.
5. If a member does not agree to the amended Terms, the member may stop using the Service and request account deletion.

Article 4 (Membership Registration)
1. Membership registration is completed when the user agrees to these Terms and the Privacy Policy, completes the registration process as prescribed by the Service, and the Service approves the application.
2. Members must provide accurate and up-to-date information about themselves when registering, and must not use another person's information without authorization or provide false information.
3. The Service may refuse a membership application or later terminate the service agreement in the following cases:
  - Using another person's name or information without authorization
  - Providing false information or omitting required information
  - Applying for purposes that violate applicable laws or public order and morals
  - There is a significant risk of disrupting the stable operation of the Service

Article 5 (Account Management)
1. Members are responsible for managing their own account information and may not transfer, lend, pledge, or share it with any third party.
2. If a member becomes aware that their account has been stolen or is being used without authorization by a third party, they must immediately notify the Service and follow its instructions.
3. The Service shall not be liable for damages caused by a member's negligence in account management, unless due to the Service's intentional misconduct or gross negligence.

Article 6 (Provision of Service)
1. The Service provides the following features:
  - Uploading school notices or documents
  - Extracting, translating, summarizing, and explaining document content
  - Providing action guides including required materials, submissions, and schedules
  - Providing personalized guidance based on child and school information
  - Schedule saving, notifications, and other supplementary features
2. The Service may change all or part of its features as needed for operational or technical reasons.
3. The Service may use external solutions or partner services to provide certain features.

Article 7 (Suspension or Restriction of Service)
1. The Service may restrict or suspend all or part of the Service in the following cases:
  - System inspection, maintenance, replacement, or failure recovery
  - Inability to provide normal service due to network failures, server failures, hacking, or malware
  - Natural disasters, national emergencies, power outages, or other force majeure events
2. The Service shall, in principle, provide advance notice of such events; however, if prior notice is not possible, notice may be provided afterward.

Article 8 (Member Obligations)
1. Members must comply with applicable laws, these Terms, the Privacy Policy, service usage guidelines, and notices.
2. Members must not engage in any of the following:
  - Using another person's personal information or account without authorization
  - Entering false information or continuously providing inaccurate information
  - Interfering with the operation of the Service or placing excessive load on the system
  - Reproducing, distributing, selling, or commercially using information, content, or outputs from the Service without authorization
  - Acts that violate applicable laws or public order and morals
3. If a member violates this Article, the Service may restrict account access, delete content, or suspend membership without prior notice.

Article 9 (Rights and Responsibilities Regarding Content)
1. The member who uploaded or entered Content is responsible for that Content and retains rights to it.
2. Members must hold lawful rights to the Content they upload or enter, and must not infringe upon third-party rights.
3. The Service may store, process, analyze, and display a member's Content to the extent necessary to provide the Service.
4. If a member's Content violates applicable law, infringes third-party rights, or seriously disrupts service operations, the Service may restrict, delete, or make the Content non-public without prior notice.

Article 10 (Intellectual Property)
1. Copyrights and other intellectual property rights in content created by the Service — including trademarks, logos, designs, text, software, and screen layouts included in the Service — belong to the Service or the rightful rights holder.
2. Members may not reproduce, distribute, transmit, modify, create derivative works from, or commercially use any component of the Service without the prior written consent of the Service.

Article 11 (Disclaimer)
1. The Service does not guarantee the accuracy, completeness, or legality of information and materials entered or uploaded by members.
2. Translation, summarization, explanation, action guides, and schedule information provided by the Service are reference information intended to aid member understanding, and do not replace official notices from schools or educational institutions or the content of original documents.
3. Members must directly verify original documents and official school guidance for important matters such as submission deadlines, required items, event schedules, and consent.
4. The Service is not liable for service disruptions caused by reasons attributable to the member.
5. To the extent the Service is provided free of charge, the Service shall not be liable for indirect, special, consequential, or lost-profit damages, except as otherwise required by applicable law or in cases of special circumstances.

Article 12 (Termination and Account Deletion)
1. Members may request account deletion at any time in accordance with the procedures set by the Service.
2. If a member violates these Terms or seriously disrupts service operations, the Service may request correction within a reasonable period and then terminate the service agreement. However, in urgent or serious cases of violation, restriction or termination may occur without prior notice.
3. Upon account deletion or termination, all information shall be promptly destroyed or stored separately, except for information required to be retained under applicable law and the Privacy Policy.

Article 13 (Governing Law and Jurisdiction)
1. These Terms shall be interpreted and governed by the laws of the Republic of Korea.
2. In the event of a dispute arising from use of the Service, the court of competent jurisdiction under the Civil Procedure Act shall serve as the court of first instance.

Supplementary Provision
These Terms shall take effect on April 15, 2026.`;

export default termsEn;
